[package]
name = "kormir"
version = "0.1.0"
edition = "2021"

[features]
default = []
nostr = ["dep:nostr", "dep:base64"]

[dependencies]
bitcoin = "0.29.2"
dlc = { version = "0.4.0", features = ["use-serde"] }
dlc-messages = { version = "0.4.0", features = ["use-serde"] }
lightning = "0.0.113"
nostr = { version = "0.25.0", optional = true }
base64 = { version = "0.13.1", optional = true }
serde = "1.0"

[dev-dependencies]
tokio = { version = "1.11.0", features = ["full"] }
