[package]
name = "kormir"
version = "0.1.0"
edition = "2021"

[features]
default = []
nostr = ["dep:nostr", "dep:base64"]

[dependencies]
async-trait = "0.1.74"
bitcoin = "0.29.2"
dlc = "0.4.0"
dlc-messages = "0.4.0"
lightning = "0.0.113"
nostr = { version = "0.25.0", optional = true }
base64 = { version = "0.13.1", optional = true }

[dev-dependencies]
tokio = { version = "1.11.0", features = ["full"] }
